- hosts: all
  roles:
    - ansible-role-ohmyzsh
  vars:
    ohmyzsh_users:
      - username: root
        oh_my_zsh:
          install: true
          theme: cordial
          theme_random_candidates:
            - agnoster
            - robbyrussell
          plugins:
            - ansible
            - git
            - zsh-syntax-highlighting
            - zsh-completions
          custom_plugins:
            - name: zsh-syntax-highlighting
              repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
              update: false
              version: master
            - name: zsh-completions
              repo: https://github.com/zsh-users/zsh-completions
              update: true
              version: master
          custom_themes:
            - name: powerlevel9k
              repo: https://github.com/bhilburn/powerlevel9k.git
              update: false
              version: master
            - name: cordial
              repo: https://github.com/stevelacy/cordial-zsh-theme
              update: false
              version: master
          case_sensitive: false
          hyphen_insensitive: false
          disable_auto_update: false
          disable_update_prompt: false
          update_zsh_days: 7
          disable_magic_functions: false
          disable_ls_colors: false
          disable_auto_title: false
          enable_correction: false
          completion_waiting_dots: false
          disable_untracked_files_dirty: false
          history_stamps: dd/mm/yyyy
          zsh_custom: $ZSH/custom
          user_configuration: |
              # Example aliases
              alias zshconfig="vim ~/.zshrc"
              alias ohmyzsh="vim ~/.oh-my-zsh"
