---
- name: Playbook
  hosts: all
  become: true

  vars:
    omz_install_zsh: true
    users:
      - name: "root"
        #group: "lorem"
        #settings: ""
      #- name: "ipsum"
       # group: "ipsum"
        settings: |
          export PATH="/usr/local/sbin:$path"
          alias l="ls -AF"
  tasks:
    - name: Run ansible-role-oh-my-zsh.
      include_role:
        - name: "ansible-role-oh-my-zsh"
      vars:
        omz_user: "{{ item }}"
        # Only create `.zshrc` for user 'lorem'; item.settings will be
        # appended to `.zshrc` for the user 'ipsum'.
        omz_zshrc_create: "{{ (item.name == 'root') | ternary(true, false) }}"
        omz_plugins:
          - "autojump"
          - "git"
      with_items: "{{ users }}"
