---
- hosts: Test
  tasks:
    - name: Ensuring that free space on '/' is grater than 30%
      assert:
    that:
          - not {{ item.mount == '/' and ( item.size_available < item.size_total - ( item.size_total|float * 0.3 ) ) }}
      with_items: '{{ ansible_mounts }}'
      ignore_errors: yes
      register: disk_free
    -  debug: var=disk_free

    - name: Notifying the IT admin about the disk usage
      mail:
    host="smtp.myserver.com"
        port="2525"
        username="my_username"
        password="my_password"
        from="my_email"
        to="to_email"
        subject='HDD Space Low'
        body='{{ inventory_hostname }} is running low on disk space. Currently {{ disk_free.results['item']['size_available'] }}MB available.'
