---
- hosts: master
  become: yes
  tasks:
    - name: update apt packages
      apt:
          upgrade: 'yes'
          update_cache: yes
- hosts: nodes
  become: yes
  tasks:
    - name: update apt packages
      apt:
          upgrade: 'yes'
          update_cache: yes
